### ISSUE TITLE
7-parameter Datum rotation and scale conversion is missing

### ISSUE THREAD

**Issue by sevar83** [ndamiens/proj4j-android#3]
Rotation must be converted to from arc seconds to radians. And 7th param must be converted from "parts per million" to "scale" format. 
OSGeo haven't fixed the trunk but released it as a stupid patch here:
http://trac.osgeo.org/proj4j/ticket/5

It's strange why such a critical flaw is not fixed in their main trunk!

**Comment by ndamiens** [comment]
Applied, i just tried to build. tell me if it's not a good fix. Thank you for issues creation. I don't use this project at this time and not working on it. But i'm pleased that it stay up to date.

**Comment by sevar83** [comment]
I can't test it really, because I've just copied the source without cloning the repo. But it looks fine.
